# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:/www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/Mu880/extract-files.sh - DO NOT EDIT



PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/pxa27x-keypad.kl:system/usr/keylayout/pxa27x-keypad.kl


PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/lib/libbinder.so:system/lib/libbinder.so \
    vendor/zte/Mu880/proprietary/lib/libgstrtp-0.10.so:system/lib/libgstrtp-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libSR_AudioIn.so:system/lib/libSR_AudioIn.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
    vendor/zte/Mu880/proprietary/lib/libtsfwloader.so:system/lib/libtsfwloader.so \
    vendor/zte/Mu880/proprietary/lib/libcodecmpeg4enc.so:system/lib/libcodecmpeg4enc.so \
    vendor/zte/Mu880/proprietary/lib/libvtengine_client.so:system/lib/libvtengine_client.so \
    vendor/zte/Mu880/proprietary/lib/libemoji.so:system/lib/libemoji.so \
    vendor/zte/Mu880/proprietary/lib/libcmmb_playengine.so:system/lib/libcmmb_playengine.so \
    vendor/zte/Mu880/proprietary/lib/libm.so:system/lib/libm.so \
    vendor/zte/Mu880/proprietary/lib/libeng_mdtv_jni.so:system/lib/libeng_mdtv_jni.so \
    vendor/zte/Mu880/proprietary/lib/libstdc++.so:system/lib/libstdc++.so \
    vendor/zte/Mu880/proprietary/lib/libgio-2.0.so:system/lib/libgio-2.0.so \
    vendor/zte/Mu880/proprietary/lib/libUIModelJNI_Sim.so:system/lib/libUIModelJNI_Sim.so \
    vendor/zte/Mu880/proprietary/lib/libzte_wlan.so:system/lib/libzte_wlan.so \
    vendor/zte/Mu880/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/zte/Mu880/proprietary/lib/libgstnet-0.10.so:system/lib/libgstnet-0.10.so \
    vendor/zte/Mu880/proprietary/lib/liba2dp.so:system/lib/liba2dp.so \
    vendor/zte/Mu880/proprietary/lib/libcodecwmadec.so:system/lib/libcodecwmadec.so \
    vendor/zte/Mu880/proprietary/lib/libcutils.so:system/lib/libcutils.so \
    vendor/zte/Mu880/proprietary/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/zte/Mu880/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/zte/Mu880/proprietary/lib/libgui.so:system/lib/libgui.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_mp4localreg.so:system/lib/libopencore_mp4localreg.so \
    vendor/zte/Mu880/proprietary/lib/libglib-2.0.so:system/lib/libglib-2.0.so \
    vendor/zte/Mu880/proprietary/lib/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
    vendor/zte/Mu880/proprietary/lib/libdiskconfig.so:system/lib/libdiskconfig.so \
    vendor/zte/Mu880/proprietary/lib/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/zte/Mu880/proprietary/lib/libnativehelper.so:system/lib/libnativehelper.so \
    vendor/zte/Mu880/proprietary/lib/libcodech264dec.so:system/lib/libcodech264dec.so \
    vendor/zte/Mu880/proprietary/lib/libvtengine_jni.so:system/lib/libvtengine_jni.so \
    vendor/zte/Mu880/proprietary/lib/libcodech263enc.so:system/lib/libcodech263enc.so \
    vendor/zte/Mu880/proprietary/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
    vendor/zte/Mu880/proprietary/lib/libjpeg.so:system/lib/libjpeg.so \
    vendor/zte/Mu880/proprietary/lib/libgstrtsp-0.10.so:system/lib/libgstrtsp-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libgthread-2.0.so:system/lib/libgthread-2.0.so \
    vendor/zte/Mu880/proprietary/lib/libnetworksetting.so:system/lib/libnetworksetting.so \
    vendor/zte/Mu880/proprietary/lib/libMrvlOmxWrapper.so:system/lib/libMrvlOmxWrapper.so \
    vendor/zte/Mu880/proprietary/lib/libdl.so:system/lib/libdl.so \
    vendor/zte/Mu880/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/zte/Mu880/proprietary/lib/libcodeccnmdec.so:system/lib/libcodeccnmdec.so \
    vendor/zte/Mu880/proprietary/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
    vendor/zte/Mu880/proprietary/lib/libvdmcpkg.so:system/lib/libvdmcpkg.so \
    vendor/zte/Mu880/proprietary/lib/libiprouteutil.so:system/lib/libiprouteutil.so \
    vendor/zte/Mu880/proprietary/lib/libsoundpool.so:system/lib/libsoundpool.so \
    vendor/zte/Mu880/proprietary/lib/libUIModelJNI.so:system/lib/libUIModelJNI.so \
    vendor/zte/Mu880/proprietary/lib/libusbsetting.so:system/lib/libusbsetting.so \
    vendor/zte/Mu880/proprietary/lib/libgmodule-2.0.so:system/lib/libgmodule-2.0.so \
    vendor/zte/Mu880/proprietary/lib/libFFTEm.so:system/lib/libFFTEm.so \
    vendor/zte/Mu880/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
    vendor/zte/Mu880/proprietary/lib/libnetlink.so:system/lib/libnetlink.so \
    vendor/zte/Mu880/proprietary/lib/libgstbase-0.10.so:system/lib/libgstbase-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libEGL.so:system/lib/libEGL.so \
    vendor/zte/Mu880/proprietary/lib/libthread_db.so:system/lib/libthread_db.so \
    vendor/zte/Mu880/proprietary/lib/libsmscontrol.so:system/lib/libsmscontrol.so \
    vendor/zte/Mu880/proprietary/lib/libusbtethering.so:system/lib/libusbtethering.so \
    vendor/zte/Mu880/proprietary/lib/libicuuc.so:system/lib/libicuuc.so \
    vendor/zte/Mu880/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/zte/Mu880/proprietary/lib/libcodecaacdec.so:system/lib/libcodecaacdec.so \
    vendor/zte/Mu880/proprietary/lib/libRS.so:system/lib/libRS.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_rtspreg.so:system/lib/libopencore_rtspreg.so \
    vendor/zte/Mu880/proprietary/lib/librtp_jni.so:system/lib/librtp_jni.so \
    vendor/zte/Mu880/proprietary/lib/libpxcssprofiler.so:system/lib/libpxcssprofiler.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_vtengine.so:system/lib/libopencore_vtengine.so \
    vendor/zte/Mu880/proprietary/lib/cmmb_ming_app.inp:system/lib/cmmb_ming_app.inp \
    vendor/zte/Mu880/proprietary/lib/libsensor.so:system/lib/libsensor.so \
    vendor/zte/Mu880/proprietary/lib/libacc.so:system/lib/libacc.so \
    vendor/zte/Mu880/proprietary/lib/liblabtool.so:system/lib/liblabtool.so \
    vendor/zte/Mu880/proprietary/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_common.so:system/lib/libopencore_common.so \
    vendor/zte/Mu880/proprietary/lib/libhardware.so:system/lib/libhardware.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
    vendor/zte/Mu880/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/libgst_player.so:system/lib/libgst_player.so \
    vendor/zte/Mu880/proprietary/lib/libcodech264enc.so:system/lib/libcodech264enc.so \
    vendor/zte/Mu880/proprietary/lib/libdrm1.so:system/lib/libdrm1.so \
    vendor/zte/Mu880/proprietary/lib/libFileMonitorService.so:system/lib/libFileMonitorService.so \
    vendor/zte/Mu880/proprietary/lib/libsysfs.so:system/lib/libsysfs.so \
    vendor/zte/Mu880/proprietary/lib/libpxutils.so:system/lib/libpxutils.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_downloadreg.so:system/lib/libopencore_downloadreg.so \
    vendor/zte/Mu880/proprietary/lib/libjni_pinyinime.so:system/lib/libjni_pinyinime.so \
    vendor/zte/Mu880/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_color_conversion.so:system/lib/libstagefright_color_conversion.so \
    vendor/zte/Mu880/proprietary/lib/libexpat.so:system/lib/libexpat.so \
    vendor/zte/Mu880/proprietary/lib/libbluetooth.so:system/lib/libbluetooth.so \
    vendor/zte/Mu880/proprietary/lib/libgstreamer-0.10.so:system/lib/libgstreamer-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libNetworkInfo.so:system/lib/libNetworkInfo.so \
    vendor/zte/Mu880/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/libETC1.so:system/lib/libETC1.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_mp4local.so:system/lib/libopencore_mp4local.so \
    vendor/zte/Mu880/proprietary/lib/libpmemhelper.so:system/lib/libpmemhelper.so \
    vendor/zte/Mu880/proprietary/lib/libopencorehw.so:system/lib/libopencorehw.so \
    vendor/zte/Mu880/proprietary/lib/libnetutils.so:system/lib/libnetutils.so \
    vendor/zte/Mu880/proprietary/lib/libctest.so:system/lib/libctest.so \
    vendor/zte/Mu880/proprietary/lib/libicui18n.so:system/lib/libicui18n.so \
    vendor/zte/Mu880/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/zte/Mu880/proprietary/lib/libvorbisidec.so:system/lib/libvorbisidec.so \
    vendor/zte/Mu880/proprietary/lib/libcpufreq.so:system/lib/libcpufreq.so \
    vendor/zte/Mu880/proprietary/lib/libbluedroid.so:system/lib/libbluedroid.so \
    vendor/zte/Mu880/proprietary/lib/libmedia.so:system/lib/libmedia.so \
    vendor/zte/Mu880/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/zte/Mu880/proprietary/lib/libflac.so:system/lib/libflac.so \
    vendor/zte/Mu880/proprietary/lib/libgst_recorder.so:system/lib/libgst_recorder.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_download.so:system/lib/libopencore_download.so \
    vendor/zte/Mu880/proprietary/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/zte/Mu880/proprietary/lib/libgsttag-0.10.so:system/lib/libgsttag-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
    vendor/zte/Mu880/proprietary/lib/libdrm1_jni.so:system/lib/libdrm1_jni.so \
    vendor/zte/Mu880/proprietary/lib/libcodech263dec.so:system/lib/libcodech263dec.so \
    vendor/zte/Mu880/proprietary/lib/libstlport.so:system/lib/libstlport.so \
    vendor/zte/Mu880/proprietary/lib/libaudiopath.so:system/lib/libaudiopath.so \
    vendor/zte/Mu880/proprietary/lib/libomx_mrvl_sharedlibrary.so:system/lib/libomx_mrvl_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/libsonivox.so:system/lib/libsonivox.so \
    vendor/zte/Mu880/proprietary/lib/libgstcontroller-0.10.so:system/lib/libgstcontroller-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libpxserial.so:system/lib/libpxserial.so \
    vendor/zte/Mu880/proprietary/lib/libc.so:system/lib/libc.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_player.so:system/lib/libopencore_player.so \
    vendor/zte/Mu880/proprietary/lib/libdbus.so:system/lib/libdbus.so \
    vendor/zte/Mu880/proprietary/lib/libz.so:system/lib/libz.so \
    vendor/zte/Mu880/proprietary/lib/libmtelif.so:system/lib/libmtelif.so \
    vendor/zte/Mu880/proprietary/lib/libgstinterfaces-0.10.so:system/lib/libgstinterfaces-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libcodecaacenc.so:system/lib/libcodecaacenc.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
    vendor/zte/Mu880/proprietary/lib/libcodecmpeg2dec.so:system/lib/libcodecmpeg2dec.so \
    vendor/zte/Mu880/proprietary/lib/libcnmhal.so:system/lib/libcnmhal.so \
    vendor/zte/Mu880/proprietary/lib/libgstsdp-0.10.so:system/lib/libgstsdp-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libPowerSetting.so:system/lib/libPowerSetting.so \
    vendor/zte/Mu880/proprietary/lib/libbcsthw.so:system/lib/libbcsthw.so \
    vendor/zte/Mu880/proprietary/lib/libgstpbutils-0.10.so:system/lib/libgstpbutils-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/zte/Mu880/proprietary/lib/libemodejni.so:system/lib/libemodejni.so \
    vendor/zte/Mu880/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_2way.so:system/lib/libopencore_2way.so \
    vendor/zte/Mu880/proprietary/lib/libgstapp-0.10.so:system/lib/libgstapp-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libcodecamrwbdec.so:system/lib/libcodecamrwbdec.so \
    vendor/zte/Mu880/proprietary/lib/libvdmengine.so:system/lib/libvdmengine.so \
    vendor/zte/Mu880/proprietary/lib/libcodecamrwbenc.so:system/lib/libcodecamrwbenc.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
    vendor/zte/Mu880/proprietary/lib/libzteH324m.so:system/lib/libzteH324m.so \
    vendor/zte/Mu880/proprietary/lib/libippvp.so:system/lib/libippvp.so \
    vendor/zte/Mu880/proprietary/lib/libcodecwmvdec.so:system/lib/libcodecwmvdec.so \
    vendor/zte/Mu880/proprietary/lib/libjnigraphics.so:system/lib/libjnigraphics.so \
    vendor/zte/Mu880/proprietary/lib/libMrvlOmxConfig.so:system/lib/libMrvlOmxConfig.so \
    vendor/zte/Mu880/proprietary/lib/libgstvideo-0.10.so:system/lib/libgstvideo-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/zte/Mu880/proprietary/lib/libwebcore.so:system/lib/libwebcore.so \
    vendor/zte/Mu880/proprietary/lib/libippsp.so:system/lib/libippsp.so \
    vendor/zte/Mu880/proprietary/lib/libpxsdk.so:system/lib/libpxsdk.so \
    vendor/zte/Mu880/proprietary/lib/libgstriff-0.10.so:system/lib/libgstriff-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libcodecmp3dec.so:system/lib/libcodecmp3dec.so \
    vendor/zte/Mu880/proprietary/lib/libreference-cdma-sms.so:system/lib/libreference-cdma-sms.so \
    vendor/zte/Mu880/proprietary/lib/libgstdataprotocol-0.10.so:system/lib/libgstdataprotocol-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/zte/Mu880/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
    vendor/zte/Mu880/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/zte/Mu880/proprietary/lib/libgstnetbuffer-0.10.so:system/lib/libgstnetbuffer-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libsrec_jni.so:system/lib/libsrec_jni.so \
    vendor/zte/Mu880/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/zte/Mu880/proprietary/lib/libire.so:system/lib/libire.so \
    vendor/zte/Mu880/proprietary/lib/libexif.so:system/lib/libexif.so \
    vendor/zte/Mu880/proprietary/lib/libcodecmpeg4dec.so:system/lib/libcodecmpeg4dec.so \
    vendor/zte/Mu880/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/zte/Mu880/proprietary/lib/libaudio.so:system/lib/libaudio.so \
    vendor/zte/Mu880/proprietary/lib/liblsm_gsd4t.so:system/lib/liblsm_gsd4t.so \
    vendor/zte/Mu880/proprietary/lib/libpxhsprofiler.so:system/lib/libpxhsprofiler.so \
    vendor/zte/Mu880/proprietary/lib/libttspico.so:system/lib/libttspico.so \
    vendor/zte/Mu880/proprietary/lib/libgstaudio-0.10.so:system/lib/libgstaudio-0.10.so \
    vendor/zte/Mu880/proprietary/lib/libgstmetadataretriever.so:system/lib/libgstmetadataretriever.so \
    vendor/zte/Mu880/proprietary/lib/libvdmfumo.so:system/lib/libvdmfumo.so \
    vendor/zte/Mu880/proprietary/lib/liboil.so:system/lib/liboil.so \
    vendor/zte/Mu880/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/libOrgan.so:system/lib/libOrgan.so \
    vendor/zte/Mu880/proprietary/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
    vendor/zte/Mu880/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/libeffects.so:system/lib/libeffects.so \
    vendor/zte/Mu880/proprietary/lib/libsqlite_jni.so:system/lib/libsqlite_jni.so \
    vendor/zte/Mu880/proprietary/lib/libttssynthproxy.so:system/lib/libttssynthproxy.so \
    vendor/zte/Mu880/proprietary/lib/libnfc_ndef.so:system/lib/libnfc_ndef.so \
    vendor/zte/Mu880/proprietary/lib/libgobject-2.0.so:system/lib/libgobject-2.0.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_net_support.so:system/lib/libopencore_net_support.so \
    vendor/zte/Mu880/proprietary/lib/libpxcmprofiler.so:system/lib/libpxcmprofiler.so \
    vendor/zte/Mu880/proprietary/lib/libbmm.so:system/lib/libbmm.so \
    vendor/zte/Mu880/proprietary/lib/libsystem_server.so:system/lib/libsystem_server.so \
    vendor/zte/Mu880/proprietary/lib/libbz.so:system/lib/libbz.so \
    vendor/zte/Mu880/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/zte/Mu880/proprietary/lib/libcnm.so:system/lib/libcnm.so \
    vendor/zte/Mu880/proprietary/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
    vendor/zte/Mu880/proprietary/lib/libstagefright_hardware_renderer.so:system/lib/libstagefright_hardware_renderer.so \
    vendor/zte/Mu880/proprietary/lib/libvtengineservice.so:system/lib/libvtengineservice.so \
    vendor/zte/Mu880/proprietary/lib/liblog.so:system/lib/liblog.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_author.so:system/lib/libopencore_author.so \
    vendor/zte/Mu880/proprietary/lib/libsysutils.so:system/lib/libsysutils.so \
    vendor/zte/Mu880/proprietary/lib/libcodecamrnbenc.so:system/lib/libcodecamrnbenc.so \
    vendor/zte/Mu880/proprietary/lib/liblsm_gsd3tw.so:system/lib/liblsm_gsd3tw.so \
    vendor/zte/Mu880/proprietary/lib/libcodecamrnbdec.so:system/lib/libcodecamrnbdec.so \
    vendor/zte/Mu880/proprietary/lib/libcrypto.so:system/lib/libcrypto.so \
    vendor/zte/Mu880/proprietary/lib/libvtengine.so:system/lib/libvtengine.so \
    vendor/zte/Mu880/proprietary/lib/libssl.so:system/lib/libssl.so \
    vendor/zte/Mu880/proprietary/lib/libsoup.so:system/lib/libsoup.so \
    vendor/zte/Mu880/proprietary/lib/libiconv.so:system/lib/libiconv.so \
    vendor/zte/Mu880/proprietary/lib/libcmmb.so:system/lib/libcmmb.so \
    vendor/zte/Mu880/proprietary/lib/libcodeccnmenc.so:system/lib/libcodeccnmenc.so \
    vendor/zte/Mu880/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/zte/Mu880/proprietary/lib/libvdmcscomo.so:system/lib/libvdmcscomo.so \
    vendor/zte/Mu880/proprietary/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/zte/Mu880/proprietary/lib/libmediaengine.so:system/lib/libmediaengine.so \
    vendor/zte/Mu880/proprietary/lib/libdvm.so:system/lib/libdvm.so \
    vendor/zte/Mu880/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/librs_jni.so:system/lib/librs_jni.so \
    vendor/zte/Mu880/proprietary/lib/libopencore_rtsp.so:system/lib/libopencore_rtsp.so \
    vendor/zte/Mu880/proprietary/lib/libbluetoothd.so:system/lib/libbluetoothd.so \
    vendor/zte/Mu880/proprietary/lib/libpxcmext.so:system/lib/libpxcmext.so \
    vendor/zte/Mu880/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/zte/Mu880/proprietary/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/zte/Mu880/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/zte/Mu880/proprietary/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/zte/Mu880/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/zte/Mu880/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/zte/Mu880/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/zte/Mu880/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgsth263dec.so:system/lib/gst/libgsth263dec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstmpegaudioparse.so:system/lib/gst/libgstmpegaudioparse.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstrtpmanager.so:system/lib/gst/libgstrtpmanager.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstrtp.so:system/lib/gst/libgstrtp.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstasfdemux.so:system/lib/gst/libgstasfdemux.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstapp.so:system/lib/gst/libgstapp.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstautoconvert.so:system/lib/gst/libgstautoconvert.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstffmpeg.so:system/lib/gst/libgstffmpeg.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstflumpegdemux.so:system/lib/gst/libgstflumpegdemux.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstcnmcodec.so:system/lib/gst/libgstcnmcodec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstflv.so:system/lib/gst/libgstflv.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstvideorate.so:system/lib/gst/libgstvideorate.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstdecodebin2.so:system/lib/gst/libgstdecodebin2.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudioflingersink.so:system/lib/gst/libgstaudioflingersink.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstapedemux.so:system/lib/gst/libgstapedemux.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippaacenc.so:system/lib/gst/libgstippaacenc.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgsth264dec.so:system/lib/gst/libgsth264dec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstgdp.so:system/lib/gst/libgstgdp.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstplaybin.so:system/lib/gst/libgstplaybin.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstmpeg4dec.so:system/lib/gst/libgstmpeg4dec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstudp.so:system/lib/gst/libgstudp.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstcoreindexers.so:system/lib/gst/libgstcoreindexers.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippamrwbenc.so:system/lib/gst/libgstippamrwbenc.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstautodetect.so:system/lib/gst/libgstautodetect.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstrtsp.so:system/lib/gst/libgstrtsp.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgsttypefindfunctions.so:system/lib/gst/libgsttypefindfunctions.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstcoreelements.so:system/lib/gst/libgstcoreelements.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippmpeg2dec.so:system/lib/gst/libgstippmpeg2dec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudiotestsrc.so:system/lib/gst/libgstaudiotestsrc.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstrtpmux.so:system/lib/gst/libgstrtpmux.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstmjpegdec.so:system/lib/gst/libgstmjpegdec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgsttcp.so:system/lib/gst/libgsttcp.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaacdec.so:system/lib/gst/libgstaacdec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstvolume.so:system/lib/gst/libgstvolume.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstmp3dec.so:system/lib/gst/libgstmp3dec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstmatroska.so:system/lib/gst/libgstmatroska.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstflac.so:system/lib/gst/libgstflac.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstalsasink.so:system/lib/gst/libgstalsasink.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstcmmbsplitter.so:system/lib/gst/libgstcmmbsplitter.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippcnmassist.so:system/lib/gst/libgstippcnmassist.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstqtdemux.so:system/lib/gst/libgstqtdemux.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstffmpegcolorspace.so:system/lib/gst/libgstffmpegcolorspace.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstsouphttpsrc.so:system/lib/gst/libgstsouphttpsrc.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudiorate.so:system/lib/gst/libgstaudiorate.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstmulaw.so:system/lib/gst/libgstmulaw.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippamrnbenc.so:system/lib/gst/libgstippamrnbenc.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstid3demux.so:system/lib/gst/libgstid3demux.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstwmvdec.so:system/lib/gst/libgstwmvdec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudioconvert.so:system/lib/gst/libgstaudioconvert.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstvideotestsrc.so:system/lib/gst/libgstvideotestsrc.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstvideoscale.so:system/lib/gst/libgstvideoscale.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstavi.so:system/lib/gst/libgstavi.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippamrwbdec.so:system/lib/gst/libgstippamrwbdec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstwmadec.so:system/lib/gst/libgstwmadec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudiocachesink.so:system/lib/gst/libgstaudiocachesink.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstsubparse.so:system/lib/gst/libgstsubparse.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstdecodebin.so:system/lib/gst/libgstdecodebin.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstippamrnbdec.so:system/lib/gst/libgstippamrnbdec.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstsurfaceflingersink.so:system/lib/gst/libgstsurfaceflingersink.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudioresample.so:system/lib/gst/libgstaudioresample.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstalaw.so:system/lib/gst/libgstalaw.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstwavparse.so:system/lib/gst/libgstwavparse.so \
    vendor/zte/Mu880/proprietary/lib/gst/libgstaudioparsers.so:system/lib/gst/libgstaudioparsers.so \
    vendor/zte/Mu880/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/zte/Mu880/proprietary/lib/hw/overlay.default.so:system/lib/hw/overlay.default.so \
    vendor/zte/Mu880/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/zte/Mu880/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/zte/Mu880/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/zte/Mu880/proprietary/lib/bluez-plugin/input.so:system/lib/bluez-plugin/input.so \
    vendor/zte/Mu880/proprietary/lib/bluez-plugin/audio.so:system/lib/bluez-plugin/audio.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_programs.so:system/lib/cpufreqd/cpufreqd_programs.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_exec.so:system/lib/cpufreqd/cpufreqd_exec.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_android.so:system/lib/cpufreqd/cpufreqd_android.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_input.so:system/lib/cpufreqd/cpufreqd_input.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_acpi.so:system/lib/cpufreqd/cpufreqd_acpi.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_governor_parameters.so:system/lib/cpufreqd/cpufreqd_governor_parameters.so \
    vendor/zte/Mu880/proprietary/lib/cpufreqd/cpufreqd_cpu.so:system/lib/cpufreqd/cpufreqd_cpu.so \
    vendor/zte/Mu880/proprietary/lib/modules/mlan.ko:system/lib/modules/mlan.ko \
    vendor/zte/Mu880/proprietary/lib/modules/mpdc_cm.ko:system/lib/modules/mpdc_cm.ko \
    vendor/zte/Mu880/proprietary/lib/modules/cnm.ko:system/lib/modules/cnm.ko \
    vendor/zte/Mu880/proprietary/lib/modules/mpdc_hs.ko:system/lib/modules/mpdc_hs.ko \
    vendor/zte/Mu880/proprietary/lib/modules/bt8787.ko:system/lib/modules/bt8787.ko \
    vendor/zte/Mu880/proprietary/lib/modules/sd8787.ko:system/lib/modules/sd8787.ko \
    vendor/zte/Mu880/proprietary/lib/modules/mpdc_css.ko:system/lib/modules/mpdc_css.ko \
    vendor/zte/Mu880/proprietary/lib/modules/galcore.ko:system/lib/modules/galcore.ko \
    vendor/zte/Mu880/proprietary/lib/modules/bmm.ko:system/lib/modules/bmm.ko \
    vendor/zte/Mu880/proprietary/lib/libskiagl.so:system/lib/libskiagl.so \
    vendor/zte/Mu880/proprietary/lib/libskiagl.so:obj/lib/libskiagl.so \
    vendor/zte/Mu880/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/zte/Mu880/proprietary/lib/libui.so:system/lib/libui.so \
    vendor/zte/Mu880/proprietary/lib/libpixelflinger.so:system/lib/libpixelflinger.so \
    vendor/zte/Mu880/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \



PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/app/LatinIME.apk:system/app/LatinIME.apk \
    vendor/zte/Mu880/proprietary/app/FMRadio.apk:system/app/FMRadio.apk \


#    vendor/zte/Mu880/proprietary/app/alarming.apk:system/app/alarming.apk


PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/etc/customize/tree.xml:system/etc/customize/tree.xml \
    vendor/zte/Mu880/proprietary/etc/customize/location.db:system/etc/customize/location.db

PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
    vendor/zte/Mu880/proprietary/etc/firmware/mrvl/sd8787_test.bin:system/etc/firmware/mrvl/sd8787_test.bin



PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/bin/pv2way_console_app:system/bin/pv2way_console_app \
    vendor/zte/Mu880/proprietary/bin/labtool:system/bin/labtool \
    vendor/zte/Mu880/proprietary/bin/omx_tests:system/bin/omx_tests \
    vendor/zte/Mu880/proprietary/bin/mediaserver:system/bin/mediaserver \
    vendor/zte/Mu880/proprietary/bin/applypatch:system/bin/applypatch \
    vendor/zte/Mu880/proprietary/bin/logcat:system/bin/logcat \
    vendor/zte/Mu880/proprietary/bin/app_process:system/bin/app_process \
    vendor/zte/Mu880/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
    vendor/zte/Mu880/proprietary/bin/MarvellWirelessDaemon:system/bin/MarvellWirelessDaemon \
    vendor/zte/Mu880/proprietary/bin/debuggerd:system/bin/debuggerd \
    vendor/zte/Mu880/proprietary/bin/pppd:system/bin/pppd \
    vendor/zte/Mu880/proprietary/bin/vtengineserver:system/bin/vtengineserver \
    vendor/zte/Mu880/proprietary/bin/iptables:system/bin/iptables \
    vendor/zte/Mu880/proprietary/bin/charge:system/bin/charge


PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/bin/akmd:system/bin/akmd \
    vendor/zte/Mu880/proprietary/bin/bcst_hal_test:system/bin/bcst_hal_test \
    vendor/zte/Mu880/proprietary/bin/crashhookd:system/bin/crashhookd \
    vendor/zte/Mu880/proprietary/bin/em_labtool:system/bin/em_labtool \
    vendor/zte/Mu880/proprietary/bin/emserver:system/bin/emserver \
    vendor/zte/Mu880/proprietary/bin/firewalld:system/bin/firewalld \
    vendor/zte/Mu880/proprietary/bin/fota:system/bin/fota \
    vendor/zte/Mu880/proprietary/bin/FMRadioServer:system/bin/FMRadioServer \
    vendor/zte/Mu880/proprietary/bin/cpufreqd:system/bin/cpufreqd


PRODUCT_COPY_FILES += \
    vendor/zte/Mu880/proprietary/usr/lib/alsa-lib/libasound_module_pcm_phone.so:system/usr/lib/alsa-lib/libasound_module_pcm_phone.so \
    vendor/zte/Mu880/proprietary/usr/srec/config/en.us/grammars/VoiceDialer.g2g:system/usr/srec/config/en.us/grammars/VoiceDialer.g2g \




#    vendor/zte/Mu880/proprietary/lib/libhanvonhw_v18.so:system/lib/libhanvonhw_v18.so \
#    vendor/zte/Mu880/proprietary/lib/libsogouime_jni_v18.so:system/lib/libsogouime_jni_v18.so \
#    vendor/zte/Mu880/proprietary/lib/libthemeextractor_v18.so:system/lib/libthemeextractor_v18.so \
#    vendor/zte/Mu880/proprietary/lib/libsinautility.so:system/lib/libsinautility.so \
#    vendor/zte/Mu880/proprietary/lib/libskia.so:system/lib/libskia.so \
#    vendor/zte/Mu880/proprietary/lib/libskia.so:obj/lib/libskia.so \
#    vendor/zte/Mu880/proprietary/bin/bootanimation:system/bin/bootanimation \









